name: test2

on:
  schedule:
    # - cron:  "分 時 日 月 曜日" -> (UTC) = (JST) -9 
    - cron:  "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Grow grass
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          echo "\rHello World" >> README.md
          git add README.md
          git commit -m "Hello World"
          git push origin main
